#!/usr/bin/env python3
"""Inventory scanner — generates state/inventory.md with current asset counts.

Per harness-perfection debate D3 (Gen3+Gen4 converged):
- Single source of truth for harness asset counts (replaces hand-maintained
  numbers in README.md / HARNESS-GUIDE.md that drift).
- AUTO-GENERATED header at top of state/inventory.md prevents manual edits.
- --check mode: regenerate, diff against on-disk inventory.md, exit 1 on drift.
  Suitable for CI / pre-commit / /harness-audit Phase 0.

Counts (D6 minor absorbed: skills/ direct gsd-* + skills/_gsd/* union):
- agents/*.md          (harness-* + gsd-* + others)
- commands/*.md        (harness-* + others)
- skills/_common/*.md  (lang-agnostic)
- skills/{stack}/**/*.md  (per-stack)
- scripts/validators/*.py (excluding __init__)
- scripts/lib/*.py     (excluding __init__)
- scripts/handlers/{lifecycle}/*.py  (excluding __init__, __pycache__)
- scripts/engine/*.py  (excluding __init__)
- telemetry/*.jsonl    (current categories)
- state/debates/<sid>/  (sessions)

Usage:
    python ~/.claude/scripts/engine/inventory_scan.py            # write inventory.md
    python ~/.claude/scripts/engine/inventory_scan.py --check    # CI drift detection
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent.parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from lib.paths import (  # noqa: E402
    AGENTS_DIR,
    CLAUDE_HOME,
    COMMANDS_DIR,
    ENGINE_DIR,
    HANDLERS_DIR,
    LIB_DIR,
    SKILLS_DIR,
    STATE_DIR,
    TELEMETRY_DIR,
    VALIDATORS_DIR,
    ensure_dir,
)

sys.stdout.reconfigure(encoding="utf-8")

INVENTORY_PATH = STATE_DIR / "inventory.md"

HEADER = (
    "<!-- AUTO-GENERATED by scripts/engine/inventory_scan.py — do not edit by hand. -->\n"
    "<!-- Tracked in git for drift detection (--check mode). -->\n"
    "<!-- Regenerate: `python ~/.claude/scripts/engine/inventory_scan.py` -->\n"
)


def _md_files(root: Path, recursive: bool = False) -> list[Path]:
    if not root.is_dir():
        return []
    pat = "**/*.md" if recursive else "*.md"
    return sorted(root.glob(pat))


def _py_files(root: Path) -> list[Path]:
    if not root.is_dir():
        return []
    return sorted(p for p in root.glob("*.py") if p.name != "__init__.py")


def _count_agents() -> dict[str, int]:
    files = _md_files(AGENTS_DIR)
    harness = sum(1 for p in files if p.name.startswith("harness-"))
    gsd = sum(1 for p in files if p.name.startswith("gsd-"))
    other = len(files) - harness - gsd
    return {"total": len(files), "harness": harness, "gsd": gsd, "other": other}


def _count_commands() -> dict[str, int]:
    files = _md_files(COMMANDS_DIR)
    harness = sum(1 for p in files if p.name.startswith("harness"))
    other = len(files) - harness
    return {"total": len(files), "harness": harness, "other": other}


def _count_skills() -> dict[str, int]:
    common = _md_files(SKILLS_DIR / "_common")
    # Union scan per D6: skills/ direct gsd-* dirs + future _gsd/*
    gsd_direct = sorted(
        p for p in SKILLS_DIR.iterdir()
        if p.is_dir() and p.name.startswith("gsd-")
    )
    gsd_namespaced = sorted((SKILLS_DIR / "_gsd").iterdir()) if (SKILLS_DIR / "_gsd").is_dir() else []
    # Stack subtrees (java, kotlin, typescript, flutter etc.)
    stack_dirs = sorted(
        p for p in SKILLS_DIR.iterdir()
        if p.is_dir()
        and not p.name.startswith("_")
        and not p.name.startswith("gsd-")
    )
    stack_total = sum(len(_md_files(d, recursive=True)) for d in stack_dirs)
    return {
        "common": len(common),
        "gsd_skills": len(gsd_direct) + len(gsd_namespaced),
        "stack_subtrees": len(stack_dirs),
        "stack_files": stack_total,
    }


def _count_validators() -> int:
    return len(_py_files(VALIDATORS_DIR))


def _count_lib() -> int:
    return len(_py_files(LIB_DIR))


def _count_handlers() -> dict[str, int]:
    if not HANDLERS_DIR.is_dir():
        return {}
    out: dict[str, int] = {}
    for sub in sorted(HANDLERS_DIR.iterdir()):
        if sub.is_dir() and not sub.name.startswith("_"):
            out[sub.name] = len(_py_files(sub))
    return out


def _count_engine() -> int:
    return len(_py_files(ENGINE_DIR))


def _count_telemetry() -> list[str]:
    if not TELEMETRY_DIR.is_dir():
        return []
    return sorted(p.name for p in TELEMETRY_DIR.glob("*.jsonl"))


def _count_debates() -> list[str]:
    debates = STATE_DIR / "debates"
    if not debates.is_dir():
        return []
    return sorted(p.name for p in debates.iterdir() if p.is_dir())


def _count_engine_sessions() -> dict[str, list[str]]:
    """Count sessions per registered engine (W14 — lib/engines.py registry).

    Returns {engine_name: [session_id, ...]}. Empty dirs / missing engines omitted.
    """
    from lib.engines import list_engines  # local import to avoid cycle
    out: dict[str, list[str]] = {}
    for meta in list_engines():
        d = STATE_DIR / meta.state_subdir
        if d.is_dir():
            sessions = sorted(p.name for p in d.iterdir() if p.is_dir())
            if sessions:
                out[meta.name] = sessions
    return out


def render() -> str:
    agents = _count_agents()
    commands = _count_commands()
    skills = _count_skills()

    lines: list[str] = [HEADER, "# Harness Inventory", "", "## Counts", ""]
    lines.append(f"- **agents/**: {agents['total']} (harness: {agents['harness']}, gsd: {agents['gsd']}, other: {agents['other']})")
    lines.append(f"- **commands/**: {commands['total']} (harness: {commands['harness']}, other: {commands['other']})")
    lines.append(f"- **skills/_common/**: {skills['common']}")
    lines.append(f"- **skills/ gsd-* dirs**: {skills['gsd_skills']} (direct + _gsd/ union)")
    lines.append(f"- **skills/ stack subtrees**: {skills['stack_subtrees']} dirs, {skills['stack_files']} files")
    lines.append(f"- **scripts/validators/**: {_count_validators()} .py")
    lines.append(f"- **scripts/lib/**: {_count_lib()} .py")
    lines.append(f"- **scripts/engine/**: {_count_engine()} .py")

    handlers = _count_handlers()
    if handlers:
        lines.append("- **scripts/handlers/**:")
        for name, n in handlers.items():
            lines.append(f"  - `{name}/`: {n} .py")

    telem = _count_telemetry()
    if telem:
        lines.append(f"- **telemetry/**: {len(telem)} jsonl ({', '.join(telem)})")

    debates = _count_debates()
    if debates:
        lines.append(f"- **state/debates/**: {len(debates)} sessions")
        for sid in debates:
            lines.append(f"  - `{sid}`")

    # Engine registry-driven session breakdown (W14)
    engine_sessions = _count_engine_sessions()
    other_engines = {n: s for n, s in engine_sessions.items() if n != "debate"}
    if other_engines:
        lines.append("- **engine sessions** (per `lib/engines.py` registry):")
        for engine_name, sids in other_engines.items():
            lines.append(f"  - `{engine_name}/`: {len(sids)} session(s)")

    lines.extend([
        "",
        "## Generated paths",
        "",
        f"- CLAUDE_HOME: `{CLAUDE_HOME}`",
        f"- inventory: `{INVENTORY_PATH}`",
        "",
    ])
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate state/inventory.md")
    parser.add_argument("--check", action="store_true", help="exit 1 if on-disk differs from regeneration")
    args = parser.parse_args(argv)

    new_content = render()

    if args.check:
        if not INVENTORY_PATH.is_file():
            print(f"[FAIL] {INVENTORY_PATH} missing — run without --check to generate")
            return 1
        existing = INVENTORY_PATH.read_text(encoding="utf-8")
        if existing.strip() != new_content.strip():
            print(f"[FAIL] {INVENTORY_PATH} drifted — regenerate via `python {Path(__file__).name}`")
            return 1
        print(f"[PASS] {INVENTORY_PATH} in sync")
        return 0

    ensure_dir(INVENTORY_PATH.parent)
    INVENTORY_PATH.write_text(new_content, encoding="utf-8")
    print(f"[OK] wrote {INVENTORY_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
