"""Reverse-engineer .claude/design/er/conceptual-er.md from DDL files.

Extracts:
- CREATE TABLE statements → entities
- FOREIGN KEY constraints → relationships
- Cardinality heuristic from FK uniqueness (rough — not from schema metadata)

Output passes validators/er.py basic checks (entities + relationships present).
"""
from __future__ import annotations

import re
from pathlib import Path

from .base import ExtractionResult, find_sql_sources, safe_read


_CREATE_TABLE_RE = re.compile(
    # Greedy body to absorb nested parens (VARCHAR(64) etc.); anchor closing
    # paren before ENGINE/; / EOF so we don't stop at a column-type ')'.
    r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?[`\"]?(\w+)[`\"]?\s*\((.+?)\)\s*(?:ENGINE|;|$)",
    re.IGNORECASE | re.DOTALL,
)
_FOREIGN_KEY_RE = re.compile(
    r"FOREIGN\s+KEY\s*\(\s*[`\"]?(\w+)[`\"]?\s*\)\s*REFERENCES\s+[`\"]?(\w+)[`\"]?\s*\(\s*[`\"]?(\w+)[`\"]?\s*\)",
    re.IGNORECASE,
)
# Inline FK form: column name with REFERENCES on same column line
_INLINE_FK_RE = re.compile(
    r"[`\"]?(\w+)[`\"]?\s+\w+(?:\([^)]*\))?[^,]*?REFERENCES\s+[`\"]?(\w+)[`\"]?\s*\(\s*[`\"]?(\w+)[`\"]?\s*\)",
    re.IGNORECASE,
)


class ErExtractor:
    name = "er"
    target = ".claude/design/er/conceptual-er.md"
    description = "Reverse-engineer conceptual ER diagram from DDL"

    def can_extract(self, root: Path) -> bool:
        return bool(find_sql_sources(root, max_files=1))

    def parse_er(self, root: Path) -> tuple[list, list, list]:
        """Structured DDL parse: (entities[name], relationships[(src,fk_col,dst,dst_col)],
        sources[]). Reused by extract() (markdown) AND the spec_facets er-facet
        converter (typed schema) so both share one parser. Empty if no DDL."""
        sql_files = find_sql_sources(root)
        if not sql_files:
            return [], [], []
        sources = [p.relative_to(root).as_posix() for p in sql_files[:20]]
        entities: list[str] = []
        relationships: list[tuple[str, str, str, str]] = []
        for f in sql_files:
            text = safe_read(f)
            for m in _CREATE_TABLE_RE.finditer(text):
                table = m.group(1)
                body = m.group(2)
                if table not in entities:
                    entities.append(table)
                for fk in _FOREIGN_KEY_RE.finditer(body):
                    relationships.append((table, fk.group(1), fk.group(2), fk.group(3)))
                for fk in _INLINE_FK_RE.finditer(body):
                    if "FOREIGN KEY" in body[max(0, fk.start() - 20):fk.start()]:
                        continue
                    relationships.append((table, fk.group(1), fk.group(2), fk.group(3)))
        return entities, relationships, sources

    def extract(self, root: Path) -> ExtractionResult:
        entities, relationships, sources = self.parse_er(root)
        if not entities and not sources:
            return ExtractionResult(
                extractor=self.name, target=self.target,
                content="# Conceptual ER (no DDL found)\n",
                confidence=0.0, notes=["no .sql files under known DDL paths"],
            )

        signals = (1 if entities else 0) + (1 if relationships else 0)
        confidence = round(0.4 + 0.3 * signals, 2)

        notes = [f"entities={len(entities)} relationships={len(relationships)}"]
        if not entities:
            notes.append("no CREATE TABLE statements detected")

        content = self._render(entities, relationships)

        return ExtractionResult(
            extractor=self.name,
            target=self.target,
            content=content,
            confidence=min(confidence, 1.0),
            notes=notes,
            sources=sources,
        )

    def _render(self, entities: list[str], rels: list[tuple[str, str, str, str]]) -> str:
        L = []
        L.append("<!-- AUTO-GENERATED by lib.extractors.er — review cardinality manually. -->")
        L.append("")
        L.append("# 개념적 ERD")
        L.append("")
        L.append("## 엔티티")
        L.append("")
        for e in entities:
            L.append(f"### {e}")
            L.append("(설명 추가 필요)")
            L.append("")
        if not entities:
            L.append("_엔티티 미발견 — DDL 경로 확인 필요_")
            L.append("")

        L.append("## 관계 (FOREIGN KEY 추출)")
        L.append("")
        if rels:
            L.append("| Source | FK column | → | Target | Target column | 추정 cardinality |")
            L.append("|---|---|---|---|---|---|")
            for src, col, dst, dst_col in rels:
                # Heuristic: FK pointing to id → N:1
                cardinality = "N:1" if dst_col.lower() == "id" else "?:?"
                L.append(f"| {src} | {col} | → | {dst} | {dst_col} | {cardinality} (추정) |")
        else:
            L.append("_FOREIGN KEY 미발견 — 인라인 FK는 일부만 잡힐 수 있음_")
        L.append("")

        L.append("## 다이어그램")
        L.append("")
        L.append("```mermaid")
        L.append("erDiagram")
        for e in entities:
            L.append(f"  {e}")
        for src, col, dst, _dc in rels:
            L.append(f'  {src} }}o--|| {dst} : "{col}"')
        L.append("```")
        L.append("")

        return "\n".join(L) + "\n"


# Lazy-registry export (matches lib.providers PROVIDER / lib.workers MULTIPLEXER pattern).
EXTRACTOR = ErExtractor
