#!/usr/bin/env python3
"""Tests for lib.validators.boilerplate (v15.25 M).

Coverage:
  - SKIPPED paths: malformed envelope, no evidence entries
  - filename heuristic only: LICENSE/.gitkeep/__init__.py basename match
  - content heuristic only: auto-generated marker, license body, short file
  - both heuristics: LICENSE filename + license body → BOILERPLATE
  - NOT_BOILERPLATE: real src file with normal name + > 100 chars content
  - worst-case aggregation: mixed evidence (1 normal + 1 LICENSE → BOILERPLATE)
  - unreadable file with boilerplate name → LIKELY_BOILERPLATE
  - lock file pattern (poetry.lock) → filename match
"""
from __future__ import annotations

import sys
import tempfile
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent.parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from lib.validators.boilerplate import (  # noqa: E402
    BoilerplateEntry,
    BoilerplateResult,
    BoilerplateVerdict,
    check,
)


def _write(path: Path, content: str) -> str:
    path.write_text(content, encoding="utf-8")
    return str(path)


# ---- SKIPPED paths ----

def test_malformed_envelope_skipped():
    assert check(None).verdict == BoilerplateVerdict.SKIPPED
    assert check("not-a-dict").verdict == BoilerplateVerdict.SKIPPED
    assert check({}).verdict == BoilerplateVerdict.SKIPPED


def test_no_evidence_skipped():
    env = {"summary": "did the thing"}
    r = check(env)
    assert r.verdict == BoilerplateVerdict.SKIPPED


# ---- NOT_BOILERPLATE (real src) ----

def test_normal_src_file_is_not_boilerplate():
    """Regular .py file with > 100 chars meaningful code → NOT_BOILERPLATE."""
    with tempfile.TemporaryDirectory() as td:
        src = _write(
            Path(td) / "service.py",
            "class UserService:\n"
            "    def __init__(self, repo):\n"
            "        self.repo = repo\n"
            "    def find(self, user_id):\n"
            "        return self.repo.get(user_id)\n",
        )
        env = {"summary": "x", "evidence": [{"file_path": src}]}
        r = check(env)
        assert r.verdict == BoilerplateVerdict.NOT_BOILERPLATE
        assert r.per_file[0].filename_match is False
        assert r.per_file[0].content_match is False


# ---- BOILERPLATE (filename AND content) ----

def test_license_filename_and_content_is_boilerplate():
    """LICENSE basename + standard MIT body → BOILERPLATE (both signals)."""
    with tempfile.TemporaryDirectory() as td:
        body = (
            "MIT License\n\n"
            "Copyright (c) 2026 Example\n\n"
            "Permission is hereby granted, free of charge, to any person obtaining a copy "
            "of this software and associated documentation files...\n"
        )
        fp = _write(Path(td) / "LICENSE", body)
        env = {"summary": "x", "evidence": [{"file_path": fp}]}
        r = check(env)
        assert r.verdict == BoilerplateVerdict.BOILERPLATE
        entry = r.per_file[0]
        assert entry.filename_match is True
        assert entry.content_match is True


def test_gitkeep_empty_is_boilerplate():
    """`.gitkeep` empty file → both filename + (empty content) match → BOILERPLATE."""
    with tempfile.TemporaryDirectory() as td:
        fp = _write(Path(td) / ".gitkeep", "")
        env = {"summary": "x", "evidence": [{"file_path": fp}]}
        r = check(env)
        assert r.verdict == BoilerplateVerdict.BOILERPLATE


def test_init_py_short_is_boilerplate():
    """__init__.py with single import → both filename + (short<100 chars)."""
    with tempfile.TemporaryDirectory() as td:
        fp = _write(Path(td) / "__init__.py", "from .module import x\n")
        env = {"summary": "x", "evidence": [{"file_path": fp}]}
        r = check(env)
        assert r.verdict == BoilerplateVerdict.BOILERPLATE


# ---- LIKELY_BOILERPLATE (only one signal) ----

def test_init_py_with_substantial_code_is_likely():
    """__init__.py with > 100 chars real code → filename match only."""
    with tempfile.TemporaryDirectory() as td:
        body = (
            "from .a import something\n"
            "from .b import another\n"
            "from .c import third\n"
            "from .d import fourth\n"
            "__all__ = ['something', 'another', 'third', 'fourth']\n"
            "__version__ = '1.0.0'\n"
        )
        fp = _write(Path(td) / "__init__.py", body)
        env = {"summary": "x", "evidence": [{"file_path": fp}]}
        r = check(env)
        assert r.verdict == BoilerplateVerdict.LIKELY_BOILERPLATE
        assert r.per_file[0].filename_match is True
        assert r.per_file[0].content_match is False


def test_autogenerated_header_in_normal_file_is_likely():
    """Normal filename but content has 'Generated by' marker → content-only match."""
    with tempfile.TemporaryDirectory() as td:
        body = (
            "# Generated by some-tool 1.2.3\n"
            "# DO NOT EDIT — regenerate with `make gen`\n\n"
            "PROTO_VERSION = 'v1'\n"
            "MESSAGE_TYPES = ['Request', 'Response', 'Event', 'Error']\n"
            "def parse(data): return data\n"
        )
        fp = _write(Path(td) / "messages_pb2.py", body)
        env = {"summary": "x", "evidence": [{"file_path": fp}]}
        r = check(env)
        assert r.verdict == BoilerplateVerdict.LIKELY_BOILERPLATE
        assert r.per_file[0].filename_match is False
        assert r.per_file[0].content_match is True


def test_lock_file_pattern_is_likely():
    """poetry.lock filename matches *.lock pattern; content arbitrary."""
    with tempfile.TemporaryDirectory() as td:
        body = (
            "[[package]]\nname = \"requests\"\nversion = \"2.31.0\"\n"
            "description = \"Python HTTP for Humans.\"\n"
            "category = \"main\"\noptional = false\npython-versions = \">=3.7\"\n"
        )
        fp = _write(Path(td) / "poetry.lock", body)
        env = {"summary": "x", "evidence": [{"file_path": fp}]}
        r = check(env)
        # filename matches lock pattern, content > 100 chars and no autogen marker
        # → filename-only signal → LIKELY_BOILERPLATE
        assert r.verdict == BoilerplateVerdict.LIKELY_BOILERPLATE
        assert r.per_file[0].filename_match is True


# ---- worst-case aggregation ----

def test_worst_case_aggregation_picks_boilerplate():
    """1 normal src + 1 LICENSE → worst=BOILERPLATE."""
    with tempfile.TemporaryDirectory() as td:
        src = _write(
            Path(td) / "service.py",
            "class S:\n    def x(self): return 1\n" + ("y\n" * 50),
        )
        lic = _write(
            Path(td) / "LICENSE",
            "MIT License\nCopyright (c) 2026\nPermission is hereby granted...\n"
            + ("x\n" * 30),
        )
        env = {
            "summary": "x",
            "evidence": [{"file_path": src}, {"file_path": lic}],
        }
        r = check(env)
        assert r.verdict == BoilerplateVerdict.BOILERPLATE
        assert len(r.per_file) == 2


# ---- unreadable file ----

def test_unreadable_boilerplate_filename_is_likely():
    """Missing file but basename matches boilerplate → LIKELY (filename-only)."""
    env = {
        "summary": "x",
        "evidence": [{"file_path": "/nonexistent/path/__init__.py"}],
    }
    r = check(env)
    assert r.verdict == BoilerplateVerdict.LIKELY_BOILERPLATE
    assert len(r.errors) == 1
    assert r.per_file[0].filename_match is True
    assert r.per_file[0].content_match is False


def test_unreadable_normal_filename_is_skipped():
    """Missing file with non-boilerplate name → silently skipped (D2 territory)."""
    env = {
        "summary": "x",
        "evidence": [{"file_path": "/nonexistent/path/service.py"}],
    }
    r = check(env)
    # No signal recorded → SKIPPED
    assert r.verdict == BoilerplateVerdict.SKIPPED
    assert len(r.errors) == 1
    assert len(r.per_file) == 0


TESTS = [
    test_malformed_envelope_skipped,
    test_no_evidence_skipped,
    test_normal_src_file_is_not_boilerplate,
    test_license_filename_and_content_is_boilerplate,
    test_gitkeep_empty_is_boilerplate,
    test_init_py_short_is_boilerplate,
    test_init_py_with_substantial_code_is_likely,
    test_autogenerated_header_in_normal_file_is_likely,
    test_lock_file_pattern_is_likely,
    test_worst_case_aggregation_picks_boilerplate,
    test_unreadable_boilerplate_filename_is_likely,
    test_unreadable_normal_filename_is_skipped,
]


def main() -> int:
    failed = 0
    for fn in TESTS:
        try:
            fn()
            print(f"  [OK] {fn.__name__}")
        except AssertionError as e:
            failed += 1
            print(f"  [FAIL] {fn.__name__}: {e}")
        except Exception as e:
            failed += 1
            print(f"  [ERROR] {fn.__name__}: {type(e).__name__}: {e}")
    if failed:
        print(f"\n[FAIL] {failed}/{len(TESTS)} tests failed")
        return 1
    print(f"\n[OK] {len(TESTS)} tests passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
