"""boilerplate — file content + filename heuristic (v15.25 M).

v15.13/v15.21 잔여 한계 직접 해소:
- semantic.py 한계 명시: "file_path가 boilerplate (LICENSE, .gitkeep) + summary가
  자연스러운 작업 서술 = 통과 (이건 file 의미적 무관성 검출이 필요)"
- cross_ref.py 한계 명시: "단일 file evidence + plausible summary (D2.5 외 추가
  정보 없음)"

본 layer는 D2.6 (cross_ref) 다음 단계 — advisory only, breaker trip 안 함.
evidence file이 그 자체로 도메인 의미를 담을 수 없는 boilerplate (LICENSE,
.gitkeep, __init__.py, auto-generated 헤더, lock 파일 등)일 때 verdict을 emit
하여 운영자 가시성 제공. `_resolve_verified_by`가 `evidence_validator_boilerplate_evidence`
grade로 ledger 표시.

설계 원칙 (lib.validators invariant 준수):
- NO LLM, NO embedder, NO ML — pure stdlib re + set + os.path
- semantic.py의 _read_file_head + _iter_evidence_paths 재사용
- False positive 허용 (짧지만 의미 있는 src code는 advisory로 처리)

검출 가능한 fabrication 클래스:
- file_path basename이 LICENSE / .gitkeep / __init__.py / *.lock 등
- 파일 본문이 auto-generated 마커 ("Generated by", "DO NOT EDIT", "@generated")
- 파일 본문이 표준 license boilerplate ("Apache License", "MIT License", ...)
- 파일 본문이 매우 짧음 (< 100 chars after strip) — placeholder 가능성

검출 불가능한 클래스 (정직):
- 회사 내부 boilerplate template (회사별 시그니처 모름)
- agent가 의도적으로 LICENSE 자체를 리뷰하는 정당 작업 (운영자 판단 필요)
- 보일러플레이트가 아닌 짧은 stub (테스트용 더미 src)

Public API:
- BoilerplateVerdict enum {NOT_BOILERPLATE, LIKELY_BOILERPLATE, BOILERPLATE, SKIPPED}
- BoilerplateEntry dataclass (per-file detail)
- BoilerplateResult dataclass
- check(envelope, *, max_file_bytes) -> BoilerplateResult
"""
from __future__ import annotations

import os
import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from .semantic import _read_file_head, _iter_evidence_paths


# --- Tunables ---------------------------------------------------------------
DEFAULT_MAX_FILE_BYTES: int = 4096

# 100 chars: __init__.py with single-line docstring + import 1줄 정도. 의미 있는
# src code는 보통 100자 초과 (함수 정의 1개라도 시그니처+body로 100자 넘김).
SHORT_FILE_CHAR_THRESHOLD: int = 100


# Filename heuristics (case-insensitive basename exact match)
_BOILERPLATE_BASENAMES: frozenset[str] = frozenset({
    # License / copyright placeholders
    "license",
    "license.txt",
    "license.md",
    "license.rst",
    "copying",
    "copying.txt",
    "notice",
    "notice.txt",
    # VCS markers
    ".gitkeep",
    ".gitignore",
    ".keep",
    # Python package markers
    "__init__.py",
    "__main__.py",
    "py.typed",
    # Project metadata files (mostly auto-generated / fixed structure)
    "authors",
    "authors.txt",
    "contributors",
    "contributors.md",
    "manifest.in",
    "requirements.txt",
    "setup.cfg",
    "changelog.md",
})

# Lock file pattern (dependency lockfiles — auto-generated, no domain content)
_LOCK_FILE_RE = re.compile(r".*\.lock$|^.*-lock\.json$", re.IGNORECASE)

# Auto-generated header markers
_AUTOGEN_PATTERNS = (
    re.compile(r"\bgenerated\s+by\b", re.IGNORECASE),
    re.compile(r"\bdo\s+not\s+(edit|modify)\b", re.IGNORECASE),
    re.compile(r"@generated\b", re.IGNORECASE),
    re.compile(r"\bauto[-\s]?generated\b", re.IGNORECASE),
)

# Standard license body markers
_LICENSE_PATTERNS = (
    re.compile(r"\bapache\s+license\b", re.IGNORECASE),
    re.compile(r"\bmit\s+license\b", re.IGNORECASE),
    re.compile(r"\bbsd\s+license\b", re.IGNORECASE),
    re.compile(r"\bgnu\s+general\s+public\s+license\b", re.IGNORECASE),
    re.compile(r"\bmozilla\s+public\s+license\b", re.IGNORECASE),
    re.compile(r"permission\s+is\s+hereby\s+granted", re.IGNORECASE),
    re.compile(r"licensed\s+under\s+the", re.IGNORECASE),
)


class BoilerplateVerdict(str, Enum):
    """4-state (+ SKIPPED) boilerplate verdict.

    str-Enum so JSONL ledger serializes the value directly.
    """

    NOT_BOILERPLATE = "not_boilerplate"
    LIKELY_BOILERPLATE = "likely_boilerplate"
    BOILERPLATE = "boilerplate"
    SKIPPED = "skipped"


@dataclass
class BoilerplateEntry:
    """Per-evidence-entry boilerplate detail (operator-visible audit trail)."""

    file_path: str
    filename_match: bool
    content_match: bool
    excerpt_len: int


@dataclass
class BoilerplateResult:
    """Aggregate boilerplate check result.

    `verdict`: worst-case across evidence
               (BOILERPLATE > LIKELY_BOILERPLATE > NOT_BOILERPLATE > SKIPPED).
    `per_file`: per-entry detail.
    `errors`: file read failures (non-fatal — verdict can still classify via
              filename heuristic alone).
    """

    verdict: BoilerplateVerdict
    per_file: list[BoilerplateEntry] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)


def _filename_is_boilerplate(file_path: str) -> bool:
    """Basename match against known boilerplate filenames + lock pattern."""
    if not isinstance(file_path, str) or not file_path:
        return False
    base = os.path.basename(file_path).lower()
    if not base:
        return False
    if base in _BOILERPLATE_BASENAMES:
        return True
    if _LOCK_FILE_RE.match(base):
        return True
    return False


def _content_is_boilerplate(excerpt: str) -> bool:
    """Content heuristic: short OR auto-generated marker OR license body."""
    if not isinstance(excerpt, str):
        return False
    stripped = excerpt.strip()
    if not stripped:
        return True  # empty placeholder
    if len(stripped) < SHORT_FILE_CHAR_THRESHOLD:
        return True
    for pat in _AUTOGEN_PATTERNS:
        if pat.search(excerpt):
            return True
    for pat in _LICENSE_PATTERNS:
        if pat.search(excerpt):
            return True
    return False


def _classify(filename_match: bool, content_match: bool) -> BoilerplateVerdict:
    if filename_match and content_match:
        return BoilerplateVerdict.BOILERPLATE
    if filename_match or content_match:
        return BoilerplateVerdict.LIKELY_BOILERPLATE
    return BoilerplateVerdict.NOT_BOILERPLATE


def _worst(a: BoilerplateVerdict, b: BoilerplateVerdict) -> BoilerplateVerdict:
    """Precedence: BOILERPLATE > LIKELY_BOILERPLATE > NOT_BOILERPLATE > SKIPPED."""
    order = {
        BoilerplateVerdict.SKIPPED: 0,
        BoilerplateVerdict.NOT_BOILERPLATE: 1,
        BoilerplateVerdict.LIKELY_BOILERPLATE: 2,
        BoilerplateVerdict.BOILERPLATE: 3,
    }
    return a if order[a] >= order[b] else b


def check(
    envelope: Any,
    *,
    max_file_bytes: int = DEFAULT_MAX_FILE_BYTES,
) -> BoilerplateResult:
    """Classify each evidence file's boilerplate status (worst-case aggregated).

    Returns SKIPPED when:
      - envelope shape malformed
      - no evidence entries with file_path

    Read failures: filename heuristic only — if filename matches, entry is
    LIKELY_BOILERPLATE (no content corroboration). If filename doesn't match
    and content is unreadable, the entry is skipped silently (error recorded).
    """
    result = BoilerplateResult(verdict=BoilerplateVerdict.SKIPPED)

    paths = list(_iter_evidence_paths(envelope))
    if not paths:
        return result

    worst = BoilerplateVerdict.SKIPPED
    saw_signal = False

    for fp in paths:
        filename_match = _filename_is_boilerplate(fp)
        excerpt, err = _read_file_head(fp, max_file_bytes)
        if err is not None:
            result.errors.append(err)
            if filename_match:
                # Filename-only signal — LIKELY (no content corroboration).
                entry_verdict = BoilerplateVerdict.LIKELY_BOILERPLATE
                worst = _worst(worst, entry_verdict)
                saw_signal = True
                result.per_file.append(BoilerplateEntry(
                    file_path=fp, filename_match=True,
                    content_match=False, excerpt_len=0,
                ))
            # else: silently skip — file missing is D2 structural territory.
            continue

        content_match = _content_is_boilerplate(excerpt)
        entry_verdict = _classify(filename_match, content_match)
        worst = _worst(worst, entry_verdict)
        saw_signal = True
        result.per_file.append(BoilerplateEntry(
            file_path=fp,
            filename_match=filename_match,
            content_match=content_match,
            excerpt_len=len(excerpt),
        ))

    if saw_signal:
        result.verdict = worst
    return result
